version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn src.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 80:8080
    depends_on:
      - db
volumes:
  db_value:
