"""initial

Revision ID: 68c85a563755
Revises: 
Create Date: 2024-04-18 14:49:05.700379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.utils import get_toy_data_from_exel


# revision identifiers, used by Alembic.
revision: str = '68c85a563755'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    toy_table = op.create_table('toy',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('articul', sa.String(), nullable=False),
    sa.Column('gost', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('nomenclature', sa.String(), nullable=False),
    sa.Column('category_path', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('instock', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('discount_price', sa.Float(), nullable=True),
    sa.Column('razmer', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(toy_table, get_toy_data_from_exel())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toy')
    # ### end Alembic commands ###
